# Generated by Django 5.1.6 on 2026-06-01 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_bonus', '0027_alter_rewardrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='points_validity_months',
            field=models.PositiveIntegerField(blank=True, help_text='How many months points awarded for this brand stay valid before they expire. Leave empty for points that never expire. Points expire at the end of the month, this many months after the grant date.', null=True),
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='expires_at',
            field=models.DateField(blank=True, help_text="When the points in this credit expire. Set only on positive (credit) transactions, materialised from the brand's policy at grant time. Null means the points never expire.", null=True),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='type',
            field=models.CharField(choices=[('STANDARD_POINTS', 'Standard Points added'), ('REWARD_CLAIM', 'Reward Claim'), ('CREDIT_NOTE_ADJUST', 'Credit Note (dobropis) adjustment'), ('EXTRA_POINTS', 'Extra Points added'), ('ADJUSTMENT', 'Manual Adjustment'), ('EXPIRATION', 'Points expired')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reward',
            name='is_in_abra_storecards',
            field=models.BooleanField(default=True, help_text='Whether this reward exists as a storecard in ABRA. If False, ABRA submissions will use a text+price line pair (rowtype 2 + rowtype 1 cancelling discount) instead of a storecard row.'),
        ),
        migrations.AlterField(
            model_name='rewardrequest',
            name='abra_displayname',
            field=models.CharField(blank=True, default='', help_text="ABRA display name of the created order, e.g. 'OP-924/2026'.", max_length=50),
        ),
        migrations.AlterField(
            model_name='rewardrequest',
            name='abra_order_id',
            field=models.CharField(blank=True, default='', help_text="ABRA internal id of the created Received Order, e.g. 'NM2I700101'.", max_length=20),
        ),
        migrations.CreateModel(
            name='PointAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations_out', to='pa_bonus.pointstransaction')),
                ('debit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations_in', to='pa_bonus.pointstransaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='pointallocation_amount_positive')],
            },
        ),
    ]
