# Generated by Django 5.1.6 on 2026-08-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_bonus', '0031_remove_fileupload_can_manage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abrasubmission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('INVOICE', 'Standard invoice'), ('CREDIT_NOTE', 'Credit note')], max_length=15),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='status',
            field=models.CharField(choices=[('NO-CONTRACT', 'No contract'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='type',
            field=models.CharField(choices=[('STANDARD_POINTS', 'Standard points added'), ('REWARD_CLAIM', 'Reward claim'), ('CREDIT_NOTE_ADJUST', 'Credit note adjustment'), ('EXTRA_POINTS', 'Extra points added'), ('ADJUSTMENT', 'Manual adjustment'), ('EXPIRATION', 'Points expired')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reward',
            name='availability',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('AVAILABLE_LAST_UNITS', 'Available (last units)'), ('ON_DEMAND', 'On demand'), ('UNAVAILABLE', 'Unavailable')], default='ON_DEMAND', max_length=20),
        ),
        migrations.AlterField(
            model_name='rewardrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('SHIPPED', 'Shipped'), ('PARTIALLY_SHIPPED', 'Partially shipped'), ('ORDERED_FROM_SUPPLIER', 'Ordered from supplier'), ('REJECTED', 'Rejected'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled'), ('OVERDUE_INVOICE', 'Overdue invoice')], default='DRAFT', max_length=25),
        ),
    ]
