# Generated by Django 5.1.6 on 2026-09-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_bonus', '0032_alter_abrasubmission_id_alter_invoice_invoice_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='stock',
            field=models.IntegerField(blank=True, help_text='Quantity in stock as of the last stock upload. Informational only — not decremented by reward requests.', null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='availability',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('AVAILABLE_LAST_UNITS', 'Available (last units)'), ('ON_DEMAND', 'On demand'), ('TEMP_UNAVAILABLE', 'Temporarily unavailable'), ('UNAVAILABLE', 'Unavailable')], default='ON_DEMAND', max_length=20),
        ),
    ]
