# Generated by Django 5.1.6 on 2026-10-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_bonus', '0033_reward_stock_temp_unavailable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='regionrep',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='regionrep',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'region'), name='unique_active_user_region'),
        ),
        migrations.AddConstraint(
            model_name='regionrep',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('region',), name='unique_active_primary_per_region'),
        ),
    ]
