"""
Django settings for bonus project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# MY SETTINGS
LOGIN_REDIRECT_URL = 'dashboard'
LOGIN_URL = 'login'
LOGOUT_URL = 'logout'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Application definition

INSTALLED_APPS = [
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pa_bonus',
    'django_q',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'pa_bonus.middleware.UserActivityMiddleware',
]

ROOT_URLCONF = 'bonus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'pa_bonus.context_processors.contact_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'bonus.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
]

# Custom Authentication backend for using emails or usernames interchangeably
AUTHENTICATION_BACKENDS = [
    'pa_bonus.auth.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',  # Keep the default for admin
]

AUTH_USER_MODEL = 'pa_bonus.User'


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'cs'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/home/iepgvjxg/public_html/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'debug.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'pa_bonus': { 
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# ============================================================
# PENTAHO INTEGRATION
# ============================================================

# Pentaho CDA Integration
# These credentials are used to query the Pentaho reporting server
# for unpaid invoices via HTTP Basic Auth.
PENTAHO_BASE_URL = os.getenv("PENTAHO_BASE_URL", "https://report.primavera-and.cz:8080")
PENTAHO_USERNAME = os.getenv("PENTAHO_USERNAME", "")
PENTAHO_PASSWORD = os.getenv("PENTAHO_PASSWORD", "")

# These rarely change, but can be overridden if needed:
PENTAHO_CDA_PATH = "/public/PAA/karta-klienta/karta klienta.cda"
PENTAHO_DATA_ACCESS_ID = "sqlFaktury"

# =============================================================================
# ABRA GEN ERP integration
# =============================================================================
# All values default to the ones from the standalone test script so that
# development environments keep working without per-developer setup.
# Production MUST override ABRA_USERNAME and ABRA_TOKEN via environment
# variables - they are intentionally empty by default so a misconfigured
# deployment fails loudly at AbraClient() construction rather than silently
# authenticating against the wrong tenant.
#
# ABRA_PERIOD_ID changes annually in ABRA Gen. Putting it in an env var
# means the yearly rollover is a config change, not a code deploy.
# =============================================================================

ABRA_BASE_URL    = os.environ.get('ABRA_BASE_URL', 'http://37.46.208.216:881/primavera')
# USERNAME AND PASSWORD ARE DEFINED SEPARATELY IN DEVELOPMENT AND PRODUCTION SETTINGS
ABRA_DOCQUEUE_ID = os.environ.get('ABRA_DOCQUEUE_ID', 'RO00000101')
ABRA_PERIOD_ID   = os.environ.get('ABRA_PERIOD_ID', '4FI0000101')
ABRA_STORE_ID    = os.environ.get('ABRA_STORE_ID', 'C000000101')
ABRA_DIVISION_ID = os.environ.get('ABRA_DIVISION_ID', '6000000101')
ABRA_VATRATE_ID  = os.environ.get('ABRA_VATRATE_ID', '02100X0000')