"""
Django settings for bonus project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from decimal import Decimal
from pathlib import Path
import os

from decouple import config

# MY SETTINGS
LOGIN_REDIRECT_URL = 'dashboard'
LOGIN_URL = 'login'
LOGOUT_URL = 'logout'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Application definition

INSTALLED_APPS = [
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pa_bonus',
    'django_q',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'pa_bonus.middleware.UserActivityMiddleware',
]

ROOT_URLCONF = 'bonus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'pa_bonus.context_processors.contact_info',
                'pa_bonus.context_processors.features',
            ],
        },
    },
]

WSGI_APPLICATION = 'bonus.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
]

# Custom Authentication backend for using emails or usernames interchangeably
AUTHENTICATION_BACKENDS = [
    'pa_bonus.auth.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',  # Keep the default for admin
]

AUTH_USER_MODEL = 'pa_bonus.User'


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'cs'

LANGUAGES = [
    ('cs', 'Czech'),
    ('pl', 'Polish'),
    ('sk', 'Slovak'),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# =============================================================================
# DEPLOYMENT PROFILE
# =============================================================================
# Everything in this section differs between country deployments. Each value
# reads from the deployment's settings.ini / .env, and every default reproduces
# the original Czech deployment - so an existing deployment needs no config
# changes and cannot change behaviour, while a new market overrides only what
# actually differs for it.
# =============================================================================

# --- Identity -----------------------------------------------------------
BONUS_PROGRAMME_NAME = config('BONUS_PROGRAMME_NAME', default='Bonusový Program')
SUPPORT_EMAIL = config('SUPPORT_EMAIL', default='bonus@primavera-and.cz')
COMPANY_NAME = config('COMPANY_NAME', default='PRIMAVERA ANDORRANA s.r.o.')
COMPANY_PHONE = config('COMPANY_PHONE', default='+420 778 799 900')
COMPANY_STREET = config('COMPANY_STREET', default='Jinonická 804/80')
COMPANY_CITY = config('COMPANY_CITY', default='Praha 5 – Košíře')
COMPANY_ZIP = config('COMPANY_ZIP', default='158 00')

# --- Money --------------------------------------------------------------
# Currency is a business fact, not a translation: a point is worth a fixed
# amount of a specific currency, so it must never be resolved through the
# translation catalogue.
# CURRENCY_CODE is the ISO code used for accounting and integrations;
# CURRENCY_SYMBOL is what customers actually see on screen. They differ in most
# markets (CZK/Kč, PLN/zł), so both are configured rather than derived.
CURRENCY_CODE = config('CURRENCY_CODE', default='CZK')
CURRENCY_SYMBOL = config('CURRENCY_SYMBOL', default='Kč')

# VAT rate used to convert a VAT-inclusive point value into the VAT-exclusive
# unit price sent to ABRA. Czechia 0.21, Poland 0.23.
VAT_RATE = config('VAT_RATE', default='0.21', cast=Decimal)

# --- Features -----------------------------------------------------------
# Not every market runs every part of the programme. A disabled feature is
# hidden from every audience - clients, sales reps and managers alike - so
# nobody has to reason about a feature their market does not use.
FEATURES = {
    # Extra Goals: turnover targets with milestone bonuses.
    'extra_goals': config('FEATURE_EXTRA_GOALS', default=True, cast=bool),
    # Point expiration: expiry dates, warnings and expiry reports.
    'point_expiration': config('FEATURE_POINT_EXPIRATION', default=True, cast=bool),
    # SMS export: CSV generation for the smsbrana.cz bulk SMS gateway.
    'sms_export': config('FEATURE_SMS_EXPORT', default=True, cast=bool),
}

# --- SMS export ---------------------------------------------------------
# Only relevant where FEATURES['sms_export'] is on. The message body is a
# str.format template; the placeholders available to it are listed in
# SMSExportView. International dialling prefix is applied to local numbers.
SMS_MESSAGE_TEMPLATE = config(
    'SMS_MESSAGE_TEMPLATE',
    default=(
        'OS: Bonus Primavera Andorrana - na konte mate {balance} bodu. '
        'Cerpani a informace: https://bonus.primavera-and.cz/ '
        'Odhlaseni: SMS STOP na +420778799900.'
    ),
)
SMS_PHONE_COUNTRY_PREFIX = config('SMS_PHONE_COUNTRY_PREFIX', default='420')

# --- ABRA document text -------------------------------------------------
# Text written onto ABRA documents. It appears on real accounting records, so
# it must be in the language of the market the deployment serves.
ABRA_REWARD_LINE_PREFIX = config('ABRA_REWARD_LINE_PREFIX', default='Bonusový program EC/AE - ')
ABRA_DISCOUNT_LINE_TEXT = config('ABRA_DISCOUNT_LINE_TEXT', default='Bonusový program - sleva')
ABRA_DOCUMENT_DESCRIPTION = config('ABRA_DOCUMENT_DESCRIPTION', default='Bonusový program č. {request_id}')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/home/iepgvjxg/public_html/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'debug.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'pa_bonus': { 
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# ============================================================
# PENTAHO INTEGRATION
# ============================================================

# Pentaho CDA Integration
# These credentials are used to query the Pentaho reporting server
# for unpaid invoices via HTTP Basic Auth.
PENTAHO_BASE_URL = os.getenv("PENTAHO_BASE_URL", "https://report.primavera-and.cz:8080")
PENTAHO_USERNAME = os.getenv("PENTAHO_USERNAME", "")
PENTAHO_PASSWORD = os.getenv("PENTAHO_PASSWORD", "")

# These rarely change, but can be overridden if needed:
PENTAHO_CDA_PATH = "/public/PAA/karta-klienta/karta klienta.cda"
PENTAHO_DATA_ACCESS_ID = "sqlFaktury"

# Link managers follow to open a client's card in Pentaho reporting. Set to an
# empty string on deployments without a Pentaho server and the link is hidden
# instead of pointing at another country's reporting.
PENTAHO_CLIENT_CARD_URL = config(
    'PENTAHO_CLIENT_CARD_URL',
    default=(
        'https://report.primavera-and.cz:8080/pentaho/api/repos/'
        '%3Apublic%3APAA%3Akarta-klienta%3Akarta%20klienta.wcdf/generatedContent'
    ),
)

# =============================================================================
# ABRA GEN ERP integration
# =============================================================================
# All values default to the ones from the standalone test script so that
# development environments keep working without per-developer setup.
# Production MUST override ABRA_USERNAME and ABRA_TOKEN via environment
# variables - they are intentionally empty by default so a misconfigured
# deployment fails loudly at AbraClient() construction rather than silently
# authenticating against the wrong tenant.
#
# ABRA_PERIOD_ID changes annually in ABRA Gen. Putting it in an env var
# means the yearly rollover is a config change, not a code deploy.
# =============================================================================

ABRA_BASE_URL    = os.environ.get('ABRA_BASE_URL', 'http://37.46.208.216:881/primavera')
# USERNAME AND PASSWORD ARE DEFINED SEPARATELY IN DEVELOPMENT AND PRODUCTION SETTINGS
ABRA_DOCQUEUE_ID = os.environ.get('ABRA_DOCQUEUE_ID', 'RO00000101')
ABRA_PERIOD_ID   = os.environ.get('ABRA_PERIOD_ID', '4FI0000101')
ABRA_STORE_ID    = os.environ.get('ABRA_STORE_ID', 'C000000101')
ABRA_DIVISION_ID = os.environ.get('ABRA_DIVISION_ID', '6000000101')
ABRA_VATRATE_ID  = os.environ.get('ABRA_VATRATE_ID', '02100X0000')